<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="restassuredjarsuite" duration-ms="16982" started-at="2020-04-26T22:24:23 IST" finished-at="2020-04-26T22:24:40 IST">
    <groups>
    </groups>
    <test name="restassuredjartest" duration-ms="16982" started-at="2020-04-26T22:24:23 IST" finished-at="2020-04-26T22:24:40 IST">
      <class name="testCases.GetResponseFromDirectURL">
        <test-method status="PASS" signature="getUserDetails()[pri:0, instance:testCases.GetResponseFromDirectURL@26aa12dd]" name="getUserDetails" duration-ms="2897" started-at="2020-04-26T22:24:36 IST" finished-at="2020-04-26T22:24:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserDetails -->
      </class> <!-- testCases.GetResponseFromDirectURL -->
      <class name="testCases.GetStatcodeStatline">
        <test-method status="PASS" signature="getUserDetails()[pri:0, instance:testCases.GetStatcodeStatline@1c3a4799]" name="getUserDetails" duration-ms="2784" started-at="2020-04-26T22:24:29 IST" finished-at="2020-04-26T22:24:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserDetails -->
      </class> <!-- testCases.GetStatcodeStatline -->
      <class name="testCases.GetUseofJSONpath">
        <test-method status="PASS" signature="user()[pri:0, instance:testCases.GetUseofJSONpath@131276c2]" name="user" duration-ms="3794" started-at="2020-04-26T22:24:32 IST" finished-at="2020-04-26T22:24:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user -->
      </class> <!-- testCases.GetUseofJSONpath -->
      <class name="testCases.GetRespBody">
        <test-method status="PASS" signature="getUserDetails()[pri:0, instance:testCases.GetRespBody@694e1548]" name="getUserDetails" duration-ms="5042" started-at="2020-04-26T22:24:24 IST" finished-at="2020-04-26T22:24:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserDetails -->
      </class> <!-- testCases.GetRespBody -->
      <class name="testCases.DeleteTC">
        <test-method status="FAIL" signature="deleteEmpRecord()[pri:0, instance:testCases.DeleteTC@3fd7a715]" name="deleteEmpRecord" duration-ms="1626" started-at="2020-04-26T22:24:39 IST" finished-at="2020-04-26T22:24:40 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at testCases.DeleteTC.deleteEmpRecord(DeleteTC.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmpRecord -->
      </class> <!-- testCases.DeleteTC -->
    </test> <!-- restassuredjartest -->
  </suite> <!-- restassuredjarsuite -->
</testng-results>
