<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sony-VAIO" ignored="0" name="restassuredjartest" tests="15" failures="8" timestamp="2020-04-27T20:53:36 IST" time="47.11" errors="0">
  <testcase name="f" time="10.257" classname="testCases.GetReadfromExcel"/>
  <testcase name="UpdateRecords" time="23.802" classname="testCases.PutBasic"/>
  <testcase name="validateResponseBody" time="1.312" classname="testCases.PutBasic"/>
  <testcase name="validateStatusCode" time="0.007" classname="testCases.PutBasic"/>
  <testcase name="user" time="1.923" classname="testCases.PostBasic"/>
  <testcase name="validateResponseBody" time="0.057" classname="testCases.PostBasic">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostBasic.validateResponseBody(PostBasic.java:64)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateResponseBody -->
  <testcase name="validateStatusCode" time="0.002" classname="testCases.PostBasic">
    <failure type="java.lang.AssertionError" message="expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at testCases.PostBasic.validateStatusCode(PostBasic.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateStatusCode -->
  <testcase name="user" time="0.959" classname="testCases.PostFromUtilityClass"/>
  <testcase name="user" time="1.451" classname="testCases.PostfromUtilityClassHashmap"/>
  <testcase name="user" time="0.926" classname="testCases.PostDataProvider1">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostDataProvider1.user(PostDataProvider1.java:55)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase name="user" time="0.976" classname="testCases.PostDataProvider1">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostDataProvider1.user(PostDataProvider1.java:55)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase name="user" time="0.906" classname="testCases.PostDataProvider2">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostDataProvider2.user(PostDataProvider2.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase name="user" time="0.905" classname="testCases.PostDataProvider2">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostDataProvider2.user(PostDataProvider2.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase name="user" time="0.914" classname="testCases.PostDataProvider2">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostDataProvider2.user(PostDataProvider2.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase name="user" time="0.927" classname="testCases.PostFromFile">
    <failure type="java.lang.AssertionError" message="did not expect to find [OPERATION_SUCCESS] but found [null]">
      <![CDATA[java.lang.AssertionError: did not expect to find [OPERATION_SUCCESS] but found [null]
at testCases.PostFromFile.user(PostFromFile.java:48)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
</testsuite> <!-- restassuredjartest -->
